print("Welcome to the Band Name Generator.")
print("What's the name of the city you grew up in?")
str = input()
print("What's is your pet's name?")
str2 = input()
print("Your band name could " + str + " " + str2 + ".")